// Auto-generated by @data-scientist (create-dashboard skill), 10 April 2026
// Query: Average Time to Hire — InfoBip vs 7-Eleven
// Source: Pharos IUM metric_id=2358, SANDBOX (workspace export design/data-avg-time-to-hire.ts)

export interface QueryMeta {
  title: string;
  subtitle: string;
  queryDate: string;
  source: string;
  filters: string;
  environment: string;
  dateRange: string;
}

export const QUERY_META: QueryMeta = {
  title: 'Average Time to Hire: InfoBip vs 7-Eleven',
  subtitle:
    'IUM2358 — all charts and headline means use the same 10 paired months (both tenants reported)',
  queryDate: '10 April 2026',
  source: 'Pharos IUM (swh_raw.internal_usage_metrics_report_kafka) via workspace export',
  filters:
    'metric_id=2358, tenant_name in (infobip, 7eleven), wd_env_type=SANDBOX; KPIs from 10-month overlap only',
  environment: 'SANDBOX',
  dateRange: '10 paired months from Jan 2025–Feb 2026 export window',
};

export interface KPI {
  label: string;
  value: string;
  detail: string;
}

export const KPIS: KPI[] = [
  { label: 'InfoBip mean TTH', value: '41.5 days', detail: '10 paired months (aligned)' },
  { label: '7-Eleven mean TTH', value: '15.7 days', detail: 'Same 10 paired months' },
  { label: 'InfoBip median', value: '33.7 days', detail: 'Mean skewed by high months (e.g. 79)' },
  { label: '7-Eleven median', value: '15.4 days', detail: 'Paired-month window only' },
];

export interface Insight {
  finding: string;
  evidence: string;
  confidence: 'High' | 'Medium' | 'Low';
  confidenceReason: string;
  recommendation: string;
  caveats: string[];
}

export const INSIGHTS: Insight[] = [
  {
    finding: 'In every paired month in this export, 7-Eleven shows lower time to hire than InfoBip.',
    evidence:
      'Ten months (e.g. 2025-01: InfoBip 58.4 vs 7-Eleven 11.2; 2026-02: 79 vs 27.4). Line and bar charts use this set.',
    confidence: 'High',
    confidenceReason: 'Consistent direction across all 10 overlaps; no paired month reverses the gap.',
    recommendation:
      'Charts and KPI means are on an aligned 10-month window; do not imply causation — volume, role mix, and configuration differ.',
    caveats: [
      'SANDBOX snapshot; PROD may differ',
      'No statistical test for tenant-level “significance” without modelling confounders',
    ],
  },
  {
    finding: 'Headline means and medians are comparable because both tenants use the same 10 months here.',
    evidence:
      '7-Eleven’s full Pharos export can include extra months, but this dashboard restricts 7-Eleven to the same paired months as InfoBip for a fair comparison.',
    confidence: 'High',
    confidenceReason: 'Metrics are computed only from OVERLAP_* series.',
    recommendation:
      'If you need 7-Eleven’s full-tenant history, query Pharos separately; do not mix with this 10-month view without labelling.',
    caveats: ['Export rules drop zero or missing metric months per tenant'],
  },
  {
    finding: 'InfoBip is more volatile than 7-Eleven on these paired months.',
    evidence:
      'InfoBip range 24–79 days; 7-Eleven range 11.2–27.4 days on the same calendar months.',
    confidence: 'Medium',
    confidenceReason: 'Descriptive spread only; no variance test.',
    recommendation: 'If benchmarking InfoBip, show rolling average or IQR, not a single month.',
    caveats: ['Single-tenant noise can dominate small samples'],
  },
];

/** Months where both tenants have a value in the export (line + grouped bar + KPI means) */
export const OVERLAP_LABELS = [
  '2025-01',
  '2025-03',
  '2025-04',
  '2025-05',
  '2025-06',
  '2025-07',
  '2025-08',
  '2025-09',
  '2025-10',
  '2026-02',
];

export const OVERLAP_INFOBIP = [58.4, 24, 33, 33, 55.5, 45, 28.7, 24, 34.3, 79];

export const OVERLAP_SEVEN_ELEVEN = [11.2, 11.6, 11.7, 16.7, 15.6, 15.2, 13.4, 14.2, 19.8, 27.4];

export const MEAN_COMPARISON_LABELS = ['InfoBip (n=10)', '7-Eleven (n=10)'];

export const MEAN_COMPARISON_VALUES = [41.5, 15.7];
