/**
 * Employment Agreement BP step-level metrics (PROD, Pharos).
 * BP type: Propose Compensation Offer/Employment Agreement
 * Source: dw.swh.bp_event_record_stats
 * Generated by scripts/build_employment_agreement_dashboard_data.py
 */

import { LABELS } from './data-bp-durations';

export interface EaStepMonthlyPoint {
  ym: string;
  volume: number;
  tenants: number;
  avgHours: number | null;
  p90Hours: number | null;
}

export const EMPLOYMENT_AGREEMENT_STEPS_SOURCE = {
  table: 'dw.swh.bp_event_record_stats',
  environment: 'PROD',
  bpTypeId: "Propose Compensation Offer/Employment Agreement",
  monthRange: '2025-04 to 2026-03',
} as const;

/** Curated tasks aligned to Offer dashboard (document, integration, approval). */
export const EA_DOCUMENT_STEP_TASKS = [
 "Review Documents",
  "Review Writer Generated Document",
  "Add Documents",
  "Generate Document",
  "Manage Attachments",
  "Put Review Document Event for eSignature Integration (Web Service)",
] as const;

export const EA_INTEGRATION_STEP_TASKS = [
  "Complete Questionnaire",
  "Employment Agreement (Web Service)",
  "Offer (Web Service)",
] as const;

export const EA_APPROVAL_STEP_TASKS = [
  "Bulk Approve",
  "Approve Business Process (Web Service)",
] as const;

export const employmentAgreementStepMonthly: Record<string, EaStepMonthlyPoint[]> = {
  "Add Documents": [{"ym":"2025-04", "volume":244, "tenants":4, "avgHours":null, "p90Hours":null}, {"ym":"2025-05", "volume":232, "tenants":3, "avgHours":null, "p90Hours":null}, {"ym":"2025-06", "volume":314, "tenants":3, "avgHours":null, "p90Hours":null}, {"ym":"2025-07", "volume":268, "tenants":4, "avgHours":null, "p90Hours":null}, {"ym":"2025-08", "volume":188, "tenants":3, "avgHours":null, "p90Hours":null}, {"ym":"2025-09", "volume":146, "tenants":5, "avgHours":null, "p90Hours":null}, {"ym":"2025-10", "volume":176, "tenants":2, "avgHours":null, "p90Hours":null}, {"ym":"2025-11", "volume":148, "tenants":4, "avgHours":null, "p90Hours":null}, {"ym":"2025-12", "volume":147, "tenants":3, "avgHours":null, "p90Hours":null}, {"ym":"2026-01", "volume":205, "tenants":2, "avgHours":null, "p90Hours":null}, {"ym":"2026-02", "volume":158, "tenants":3, "avgHours":null, "p90Hours":null}, {"ym":"2026-03", "volume":232, "tenants":2, "avgHours":null, "p90Hours":null}],
  "Approve Business Process (Web Service)": [{"ym":"2025-04", "volume":162, "tenants":1, "avgHours":null, "p90Hours":null}, {"ym":"2025-05", "volume":46, "tenants":1, "avgHours":null, "p90Hours":null}],
  "Bulk Approve": [{"ym":"2025-04", "volume":1105, "tenants":8, "avgHours":14.291, "p90Hours":42.047}, {"ym":"2025-05", "volume":852, "tenants":11, "avgHours":12.894, "p90Hours":42.13}, {"ym":"2025-06", "volume":1363, "tenants":9, "avgHours":8.692, "p90Hours":23.685}, {"ym":"2025-07", "volume":1241, "tenants":9, "avgHours":8.027, "p90Hours":18.888}, {"ym":"2025-08", "volume":1287, "tenants":8, "avgHours":8.115, "p90Hours":20.278}, {"ym":"2025-09", "volume":1399, "tenants":11, "avgHours":5.59, "p90Hours":17.044}, {"ym":"2025-10", "volume":1220, "tenants":10, "avgHours":6.073, "p90Hours":17.2}, {"ym":"2025-11", "volume":1142, "tenants":7, "avgHours":5.489, "p90Hours":17.588}, {"ym":"2025-12", "volume":653, "tenants":8, "avgHours":10.035, "p90Hours":22.144}, {"ym":"2026-01", "volume":955, "tenants":9, "avgHours":7.562, "p90Hours":22.506}, {"ym":"2026-02", "volume":892, "tenants":10, "avgHours":6.303, "p90Hours":16.673}, {"ym":"2026-03", "volume":882, "tenants":11, "avgHours":5.76, "p90Hours":16.656}],
  "Complete Questionnaire": [{"ym":"2025-04", "volume":119009, "tenants":281, "avgHours":null, "p90Hours":null}, {"ym":"2025-05", "volume":117358, "tenants":275, "avgHours":null, "p90Hours":null}, {"ym":"2025-06", "volume":110025, "tenants":295, "avgHours":null, "p90Hours":null}, {"ym":"2025-07", "volume":116008, "tenants":300, "avgHours":null, "p90Hours":null}, {"ym":"2025-08", "volume":109600, "tenants":296, "avgHours":null, "p90Hours":null}, {"ym":"2025-09", "volume":113381, "tenants":299, "avgHours":null, "p90Hours":null}, {"ym":"2025-10", "volume":112753, "tenants":299, "avgHours":null, "p90Hours":null}, {"ym":"2025-11", "volume":98896, "tenants":303, "avgHours":null, "p90Hours":null}, {"ym":"2025-12", "volume":104243, "tenants":307, "avgHours":null, "p90Hours":null}, {"ym":"2026-01", "volume":101596, "tenants":309, "avgHours":null, "p90Hours":null}, {"ym":"2026-02", "volume":109460, "tenants":323, "avgHours":null, "p90Hours":null}, {"ym":"2026-03", "volume":131446, "tenants":331, "avgHours":null, "p90Hours":null}],
  "Employment Agreement (Web Service)": [{"ym":"2025-04", "volume":886, "tenants":3, "avgHours":null, "p90Hours":null}, {"ym":"2025-05", "volume":778, "tenants":4, "avgHours":null, "p90Hours":null}, {"ym":"2025-06", "volume":866, "tenants":3, "avgHours":null, "p90Hours":null}, {"ym":"2025-07", "volume":1227, "tenants":3, "avgHours":null, "p90Hours":null}, {"ym":"2025-08", "volume":1032, "tenants":4, "avgHours":null, "p90Hours":null}, {"ym":"2025-09", "volume":1027, "tenants":3, "avgHours":null, "p90Hours":null}, {"ym":"2025-10", "volume":938, "tenants":3, "avgHours":null, "p90Hours":null}, {"ym":"2025-11", "volume":794, "tenants":4, "avgHours":null, "p90Hours":null}, {"ym":"2025-12", "volume":438, "tenants":3, "avgHours":null, "p90Hours":null}, {"ym":"2026-01", "volume":940, "tenants":3, "avgHours":null, "p90Hours":null}, {"ym":"2026-02", "volume":724, "tenants":3, "avgHours":null, "p90Hours":null}, {"ym":"2026-03", "volume":786, "tenants":3, "avgHours":null, "p90Hours":null}],
  "Generate Document": [{"ym":"2025-04", "volume":486, "tenants":4, "avgHours":null, "p90Hours":null}, {"ym":"2025-05", "volume":440, "tenants":5, "avgHours":null, "p90Hours":null}, {"ym":"2025-06", "volume":438, "tenants":4, "avgHours":null, "p90Hours":null}, {"ym":"2025-07", "volume":454, "tenants":5, "avgHours":null, "p90Hours":null}, {"ym":"2025-08", "volume":354, "tenants":4, "avgHours":null, "p90Hours":null}, {"ym":"2025-09", "volume":336, "tenants":4, "avgHours":null, "p90Hours":null}, {"ym":"2025-10", "volume":322, "tenants":3, "avgHours":null, "p90Hours":null}, {"ym":"2025-11", "volume":306, "tenants":4, "avgHours":null, "p90Hours":null}, {"ym":"2025-12", "volume":310, "tenants":4, "avgHours":null, "p90Hours":null}, {"ym":"2026-01", "volume":262, "tenants":3, "avgHours":null, "p90Hours":null}, {"ym":"2026-02", "volume":290, "tenants":4, "avgHours":null, "p90Hours":null}, {"ym":"2026-03", "volume":486, "tenants":3, "avgHours":null, "p90Hours":null}],
  "Manage Attachments": [{"ym":"2025-04", "volume":3, "tenants":3, "avgHours":null, "p90Hours":null}, {"ym":"2025-05", "volume":1, "tenants":1, "avgHours":null, "p90Hours":null}, {"ym":"2025-06", "volume":2, "tenants":2, "avgHours":null, "p90Hours":null}, {"ym":"2025-07", "volume":1, "tenants":1, "avgHours":null, "p90Hours":null}, {"ym":"2025-08", "volume":3, "tenants":3, "avgHours":null, "p90Hours":null}, {"ym":"2025-09", "volume":6, "tenants":4, "avgHours":null, "p90Hours":null}, {"ym":"2025-10", "volume":1, "tenants":1, "avgHours":null, "p90Hours":null}, {"ym":"2025-11", "volume":1, "tenants":1, "avgHours":null, "p90Hours":null}, {"ym":"2026-01", "volume":1, "tenants":1, "avgHours":null, "p90Hours":null}, {"ym":"2026-02", "volume":1, "tenants":1, "avgHours":null, "p90Hours":null}, {"ym":"2026-03", "volume":2, "tenants":2, "avgHours":null, "p90Hours":null}],
  "Offer (Web Service)": [{"ym":"2025-04", "volume":94524, "tenants":20, "avgHours":null, "p90Hours":null}, {"ym":"2025-05", "volume":101567, "tenants":19, "avgHours":null, "p90Hours":null}, {"ym":"2025-06", "volume":102866, "tenants":19, "avgHours":null, "p90Hours":null}, {"ym":"2025-07", "volume":120863, "tenants":18, "avgHours":null, "p90Hours":null}, {"ym":"2025-08", "volume":125252, "tenants":21, "avgHours":null, "p90Hours":null}, {"ym":"2025-09", "volume":122493, "tenants":19, "avgHours":null, "p90Hours":null}, {"ym":"2025-10", "volume":172501, "tenants":21, "avgHours":null, "p90Hours":null}, {"ym":"2025-11", "volume":127078, "tenants":23, "avgHours":null, "p90Hours":null}, {"ym":"2025-12", "volume":73216, "tenants":20, "avgHours":null, "p90Hours":null}, {"ym":"2026-01", "volume":77436, "tenants":20, "avgHours":null, "p90Hours":null}, {"ym":"2026-02", "volume":80595, "tenants":20, "avgHours":null, "p90Hours":null}, {"ym":"2026-03", "volume":98942, "tenants":25, "avgHours":null, "p90Hours":null}],
  "Put Review Document Event for eSignature Integration (Web Service)": [{"ym":"2025-04", "volume":874, "tenants":3, "avgHours":null, "p90Hours":null}, {"ym":"2025-05", "volume":896, "tenants":3, "avgHours":null, "p90Hours":null}, {"ym":"2025-06", "volume":2244, "tenants":3, "avgHours":null, "p90Hours":null}, {"ym":"2025-07", "volume":1698, "tenants":3, "avgHours":null, "p90Hours":null}, {"ym":"2025-08", "volume":1332, "tenants":3, "avgHours":null, "p90Hours":null}, {"ym":"2025-09", "volume":1478, "tenants":3, "avgHours":null, "p90Hours":null}, {"ym":"2025-10", "volume":4626, "tenants":3, "avgHours":null, "p90Hours":null}, {"ym":"2025-11", "volume":4474, "tenants":3, "avgHours":null, "p90Hours":null}, {"ym":"2025-12", "volume":508, "tenants":3, "avgHours":null, "p90Hours":null}, {"ym":"2026-01", "volume":448, "tenants":3, "avgHours":null, "p90Hours":null}, {"ym":"2026-02", "volume":392, "tenants":3, "avgHours":null, "p90Hours":null}, {"ym":"2026-03", "volume":408, "tenants":3, "avgHours":null, "p90Hours":null}],
  "Review Documents": [{"ym":"2025-04", "volume":5313, "tenants":27, "avgHours":5.415, "p90Hours":15.86}, {"ym":"2025-05", "volume":5706, "tenants":31, "avgHours":1.39, "p90Hours":2.775}, {"ym":"2025-06", "volume":5348, "tenants":28, "avgHours":30.601, "p90Hours":113.002}, {"ym":"2025-07", "volume":5761, "tenants":29, "avgHours":0.761, "p90Hours":1.936}, {"ym":"2025-08", "volume":5320, "tenants":31, "avgHours":85.235, "p90Hours":477.348}, {"ym":"2025-09", "volume":5243, "tenants":29, "avgHours":null, "p90Hours":null}, {"ym":"2025-10", "volume":5925, "tenants":29, "avgHours":3.659, "p90Hours":14.735}, {"ym":"2025-11", "volume":5121, "tenants":33, "avgHours":11.138, "p90Hours":74.523}, {"ym":"2025-12", "volume":4473, "tenants":36, "avgHours":9.185, "p90Hours":66.466}, {"ym":"2026-01", "volume":4567, "tenants":31, "avgHours":10.308, "p90Hours":19.946}, {"ym":"2026-02", "volume":5021, "tenants":31, "avgHours":12.293, "p90Hours":47.668}, {"ym":"2026-03", "volume":5619, "tenants":36, "avgHours":17.422, "p90Hours":67.138}],
  "Review Writer Generated Document": [{"ym":"2025-04", "volume":1606, "tenants":10, "avgHours":null, "p90Hours":null}, {"ym":"2025-05", "volume":1472, "tenants":9, "avgHours":null, "p90Hours":null}, {"ym":"2025-06", "volume":1582, "tenants":9, "avgHours":null, "p90Hours":null}, {"ym":"2025-07", "volume":1624, "tenants":10, "avgHours":null, "p90Hours":null}, {"ym":"2025-08", "volume":1510, "tenants":10, "avgHours":null, "p90Hours":null}, {"ym":"2025-09", "volume":1478, "tenants":10, "avgHours":null, "p90Hours":null}, {"ym":"2025-10", "volume":1634, "tenants":9, "avgHours":null, "p90Hours":null}, {"ym":"2025-11", "volume":1240, "tenants":9, "avgHours":null, "p90Hours":null}, {"ym":"2025-12", "volume":1322, "tenants":9, "avgHours":null, "p90Hours":null}, {"ym":"2026-01", "volume":1420, "tenants":8, "avgHours":null, "p90Hours":null}, {"ym":"2026-02", "volume":1538, "tenants":8, "avgHours":null, "p90Hours":null}, {"ym":"2026-03", "volume":1864, "tenants":7, "avgHours":null, "p90Hours":null}],
};

export function eaStepsLatestYm(): string {
 return LABELS[LABELS.length - 1]!;
}

export function bottleneckScoreEa(volume: number, avgHours: number | null): number {
  if (avgHours == null || avgHours <= 0) return 0;
  const v = Math.max(0, volume);
  return avgHours * Math.log10(1 + v);
}

export type EaBottleneckRow = {
  taskName: string;
  group: 'document' | 'integration' | 'approval';
  latestYm: string;
  volume: number;
  tenants: number;
  avgHours: number | null;
  p90Hours: number | null;
  score: number;
  dominantFactor: 'volume' | 'duration' | 'low_tenant_coverage';
};

function pointEa(task: string, ym: string): EaStepMonthlyPoint | undefined {
  return employmentAgreementStepMonthly[task]?.find(p => p.ym === ym);
}

export function rankEmploymentAgreementBottlenecks(ym: string = eaStepsLatestYm()): EaBottleneckRow[] {
  const rows: EaBottleneckRow[] = [];
  const push = (taskName: string, group: EaBottleneckRow['group']) => {
    const p = pointEa(taskName, ym);
    if (!p) return;
    const score = bottleneckScoreEa(p.volume, p.avgHours);
    let dominantFactor: EaBottleneckRow['dominantFactor'] = 'volume';
    if (p.tenants > 0 && p.volume / p.tenants < 50) dominantFactor = 'low_tenant_coverage';
    if (p.avgHours != null && p.avgHours >= 8 && p.volume > 5000) dominantFactor = 'duration';
    rows.push({ taskName, group, latestYm: ym, volume: p.volume, tenants: p.tenants, avgHours: p.avgHours, p90Hours: p.p90Hours, score, dominantFactor });
  };
  for (const t of EA_DOCUMENT_STEP_TASKS) push(t, 'document');
  for (const t of EA_INTEGRATION_STEP_TASKS) push(t, 'integration');
  for (const t of EA_APPROVAL_STEP_TASKS) push(t, 'approval');
  return rows.sort((a, b) => b.score - a.score);
}

export const HAS_EA_APPROVAL_CHARTS = true;

