// Generated by scripts/build_value_realization_ium_snapshot.py
// Do not edit manually.

export type ResolutionStatus = 'live' | 'legacy-unresolved';

export interface MetricPoint {
  ym: string;
  tenants: number;
  avgValue: number | null;
}

export interface MetricSnapshot {
  key: string;
  label: string;
  metricName: string | null;
  metricId: number | null;
  environment: 'SANDBOX' | 'PROD' | 'MIXED' | 'UNKNOWN';
  resolution: ResolutionStatus;
  latestYm: string | null;
  latestValue: number | null;
  latestTenants: number;
  unit: 'days' | 'count';
  description: string;
  notes: string[];
  series: MetricPoint[];
}

export const QUERY_META = {
  "title": "Value Realisation IUM Snapshot",
  "source": "Pharos internal_usage_metrics_report_kafka",
  "resolutionMode": "metric_name_first",
  "queryDate": "15 Apr 2026",
  "note": "Generated by scripts/build_value_realization_ium_snapshot.py. Live metrics are resolved by metric_name before displaying the currently observed metric_id. Environment labels reflect what the currently accessible warehouse returned for each metric name."
} as const;

export const VALUE_REALIZATION_IUMS: Record<string, MetricSnapshot> = {
  "timeToHire": {
    "key": "timeToHire",
    "label": "Avg Time to Hire",
    "metricName": "Average Time to Hire",
    "metricId": 2358,
    "environment": "SANDBOX",
    "resolution": "live",
    "latestYm": "2026-02",
    "latestValue": 40.84743501038353,
    "latestTenants": 5950,
    "unit": "days",
    "description": "Average calendar days from first job posting date to latest offer accepted date per job requisition. Excludes Employment Agreement.",
    "notes": [
      "Resolved live by metric_name from internal_usage_metrics_report_kafka.",
      "Uses the latest month returned by Pharos for this metric."
    ],
    "series": [
      {
        "ym": "2023-06",
        "tenants": 5498,
        "avgValue": 31.13540001760116
      },
      {
        "ym": "2023-07",
        "tenants": 5498,
        "avgValue": 31.93994995282163
      },
      {
        "ym": "2023-08",
        "tenants": 5498,
        "avgValue": 31.79711347740882
      },
      {
        "ym": "2023-09",
        "tenants": 5498,
        "avgValue": 31.485796849936502
      },
      {
        "ym": "2023-10",
        "tenants": 5498,
        "avgValue": 32.45463737906008
      },
      {
        "ym": "2023-11",
        "tenants": 5522,
        "avgValue": 36.82203293394682
      },
      {
        "ym": "2023-12",
        "tenants": 5498,
        "avgValue": 34.024753519506454
      },
      {
        "ym": "2024-01",
        "tenants": 5498,
        "avgValue": 35.39860052367994
      },
      {
        "ym": "2024-02",
        "tenants": 5498,
        "avgValue": 34.5231073692615
      },
      {
        "ym": "2024-03",
        "tenants": 5498,
        "avgValue": 33.892664400653246
      },
      {
        "ym": "2024-04",
        "tenants": 5498,
        "avgValue": 35.5314555314825
      },
      {
        "ym": "2024-05",
        "tenants": 5498,
        "avgValue": 34.996713238069304
      },
      {
        "ym": "2024-06",
        "tenants": 5498,
        "avgValue": 34.60066867773549
      },
      {
        "ym": "2024-07",
        "tenants": 5498,
        "avgValue": 35.45978652622028
      },
      {
        "ym": "2024-08",
        "tenants": 5498,
        "avgValue": 36.16894324333149
      },
      {
        "ym": "2024-09",
        "tenants": 5498,
        "avgValue": 35.652642476501555
      },
      {
        "ym": "2024-10",
        "tenants": 5498,
        "avgValue": 37.012968484667034
      },
      {
        "ym": "2024-11",
        "tenants": 5498,
        "avgValue": 36.740705592632914
      },
      {
        "ym": "2024-12",
        "tenants": 5498,
        "avgValue": 38.74105682126654
      },
      {
        "ym": "2025-01",
        "tenants": 5498,
        "avgValue": 40.70041144964617
      },
      {
        "ym": "2025-02",
        "tenants": 5498,
        "avgValue": 39.74943548920336
      },
      {
        "ym": "2025-03",
        "tenants": 5498,
        "avgValue": 39.13296004645258
      },
      {
        "ym": "2025-04",
        "tenants": 5498,
        "avgValue": 40.32252965505351
      },
      {
        "ym": "2025-05",
        "tenants": 5501,
        "avgValue": 41.17456364715644
      },
      {
        "ym": "2025-06",
        "tenants": 5449,
        "avgValue": 40.92936222260836
      },
      {
        "ym": "2025-07",
        "tenants": 5472,
        "avgValue": 40.795109522420695
      },
      {
        "ym": "2025-08",
        "tenants": 5478,
        "avgValue": 39.63683380032439
      },
      {
        "ym": "2025-09",
        "tenants": 5645,
        "avgValue": 38.78438733333335
      },
      {
        "ym": "2025-10",
        "tenants": 5674,
        "avgValue": 38.489803515454845
      },
      {
        "ym": "2025-11",
        "tenants": 5782,
        "avgValue": 38.73432376448273
      },
      {
        "ym": "2025-12",
        "tenants": 4966,
        "avgValue": 37.72670333713256
      },
      {
        "ym": "2026-01",
        "tenants": 4854,
        "avgValue": 40.93341956474453
      },
      {
        "ym": "2026-02",
        "tenants": 5950,
        "avgValue": 40.84743501038353
      }
    ]
  },
  "recruiterProductivity": {
    "key": "recruiterProductivity",
    "label": "Recruiter Productivity",
    "metricName": "Recruiter Productivity",
    "metricId": 2361,
    "environment": "SANDBOX",
    "resolution": "live",
    "latestYm": "2026-02",
    "latestValue": 15.883295469149024,
    "latestTenants": 5967,
    "unit": "count",
    "description": "Average number of open job requisitions and evergreens per primary recruiter, averaged across recruiters on the tenant.",
    "notes": [
      "Resolved live by metric_name from internal_usage_metrics_report_kafka.",
      "Tracker wording is Recruiter Capacity; current live IUM metric name is Recruiter Productivity."
    ],
    "series": [
      {
        "ym": "2023-11",
        "tenants": 4250,
        "avgValue": 16.1969086652801
      },
      {
        "ym": "2025-06",
        "tenants": 5437,
        "avgValue": 15.230764445205958
      },
      {
        "ym": "2025-07",
        "tenants": 5463,
        "avgValue": 15.285806581933143
      },
      {
        "ym": "2025-08",
        "tenants": 5461,
        "avgValue": 15.62898242993364
      },
      {
        "ym": "2025-09",
        "tenants": 5581,
        "avgValue": 15.259984933377954
      },
      {
        "ym": "2025-10",
        "tenants": 5669,
        "avgValue": 15.153337577799432
      },
      {
        "ym": "2025-11",
        "tenants": 5785,
        "avgValue": 15.338320871345342
      },
      {
        "ym": "2025-12",
        "tenants": 4966,
        "avgValue": 12.98187651965985
      },
      {
        "ym": "2026-01",
        "tenants": 4862,
        "avgValue": 14.246118630465363
      },
      {
        "ym": "2026-02",
        "tenants": 5967,
        "avgValue": 15.883295469149024
      }
    ]
  },
  "offersAccepted": {
    "key": "offersAccepted",
    "label": "Offers Accepted",
    "metricName": "Number of Offers accepted.",
    "metricId": 2346,
    "environment": "SANDBOX",
    "resolution": "live",
    "latestYm": "2026-02",
    "latestValue": 130.03647314706373,
    "latestTenants": 5956,
    "unit": "count",
    "description": "Average number of offers accepted per reporting tenant for the month.",
    "notes": [
      "Resolved live by metric_name from internal_usage_metrics_report_kafka."
    ],
    "series": [
      {
        "ym": "2023-11",
        "tenants": 4256,
        "avgValue": 166.28046783625732
      },
      {
        "ym": "2025-03",
        "tenants": 5341,
        "avgValue": 149.87369207772795
      },
      {
        "ym": "2025-04",
        "tenants": 5266,
        "avgValue": 158.24085654728066
      },
      {
        "ym": "2025-05",
        "tenants": 5319,
        "avgValue": 163.25642468580003
      },
      {
        "ym": "2025-06",
        "tenants": 5397,
        "avgValue": 150.13386262924666
      },
      {
        "ym": "2025-07",
        "tenants": 5412,
        "avgValue": 165.3521931441209
      },
      {
        "ym": "2025-08",
        "tenants": 5416,
        "avgValue": 162.5331506849315
      },
      {
        "ym": "2025-09",
        "tenants": 5582,
        "avgValue": 171.70376924438153
      },
      {
        "ym": "2025-10",
        "tenants": 5642,
        "avgValue": 190.71087954786296
      },
      {
        "ym": "2025-11",
        "tenants": 5778,
        "avgValue": 145.49861973775018
      },
      {
        "ym": "2025-12",
        "tenants": 4974,
        "avgValue": 78.31180223285486
      },
      {
        "ym": "2026-01",
        "tenants": 4852,
        "avgValue": 95.85233107414254
      },
      {
        "ym": "2026-02",
        "tenants": 5956,
        "avgValue": 130.03647314706373
      }
    ]
  },
  "employmentAgreementAcceptance": {
    "key": "employmentAgreementAcceptance",
    "label": "Employment Agreement Acceptance",
    "metricName": "Employment Agreement Acceptance",
    "metricId": 2360,
    "environment": "SANDBOX",
    "resolution": "live",
    "latestYm": "2026-02",
    "latestValue": 25.861389445557784,
    "latestTenants": 5967,
    "unit": "count",
    "description": "Average number of employment agreements accepted per reporting tenant for the month.",
    "notes": [
      "Resolved live by metric_name from internal_usage_metrics_report_kafka."
    ],
    "series": [
      {
        "ym": "2023-11",
        "tenants": 4251,
        "avgValue": 30.10023419203747
      },
      {
        "ym": "2025-03",
        "tenants": 5345,
        "avgValue": 30.35642270351008
      },
      {
        "ym": "2025-04",
        "tenants": 5318,
        "avgValue": 29.56258209795459
      },
      {
        "ym": "2025-05",
        "tenants": 5352,
        "avgValue": 31.205070842654735
      },
      {
        "ym": "2025-06",
        "tenants": 5443,
        "avgValue": 32.02160776414576
      },
      {
        "ym": "2025-07",
        "tenants": 5466,
        "avgValue": 34.6735401459854
      },
      {
        "ym": "2025-08",
        "tenants": 5466,
        "avgValue": 29.99134199134199
      },
      {
        "ym": "2025-09",
        "tenants": 5640,
        "avgValue": 31.502890173410403
      },
      {
        "ym": "2025-10",
        "tenants": 5672,
        "avgValue": 32.49534352486382
      },
      {
        "ym": "2025-11",
        "tenants": 5783,
        "avgValue": 28.096879848302017
      },
      {
        "ym": "2025-12",
        "tenants": 4967,
        "avgValue": 12.098121502797762
      },
      {
        "ym": "2026-01",
        "tenants": 4855,
        "avgValue": 12.510564102564103
      },
      {
        "ym": "2026-02",
        "tenants": 5967,
        "avgValue": 25.861389445557784
      }
    ]
  },
  "internalJobApplications": {
    "key": "internalJobApplications",
    "label": "Internal Job Applications",
    "metricName": "Count of Internal Job Applications last month",
    "metricId": 2349,
    "environment": "SANDBOX",
    "resolution": "live",
    "latestYm": "2026-02",
    "latestValue": 282.94395181529194,
    "latestTenants": 5956,
    "unit": "count",
    "description": "Average number of internal job applications submitted per reporting tenant for the month.",
    "notes": [
      "Resolved live by metric_name from internal_usage_metrics_report_kafka."
    ],
    "series": [
      {
        "ym": "2023-11",
        "tenants": 4245,
        "avgValue": 274.1529080675422
      },
      {
        "ym": "2025-03",
        "tenants": 5341,
        "avgValue": 328.87201046337816
      },
      {
        "ym": "2025-04",
        "tenants": 5278,
        "avgValue": 332.5244847797315
      },
      {
        "ym": "2025-05",
        "tenants": 5333,
        "avgValue": 334.16124205013097
      },
      {
        "ym": "2025-06",
        "tenants": 5410,
        "avgValue": 300.30005525879534
      },
      {
        "ym": "2025-07",
        "tenants": 5415,
        "avgValue": 352.30521274636214
      },
      {
        "ym": "2025-08",
        "tenants": 5425,
        "avgValue": 330.77273555677056
      },
      {
        "ym": "2025-09",
        "tenants": 5584,
        "avgValue": 323.3983005841742
      },
      {
        "ym": "2025-10",
        "tenants": 5642,
        "avgValue": 327.84901995408796
      },
      {
        "ym": "2025-11",
        "tenants": 5783,
        "avgValue": 259.4142389243234
      },
      {
        "ym": "2025-12",
        "tenants": 4978,
        "avgValue": 108.05285201435979
      },
      {
        "ym": "2026-01",
        "tenants": 4855,
        "avgValue": 171.8280320131336
      },
      {
        "ym": "2026-02",
        "tenants": 5956,
        "avgValue": 282.94395181529194
      }
    ]
  },
  "timeToFill": {
    "key": "timeToFill",
    "label": "Avg Time to Fill",
    "metricName": null,
    "metricId": null,
    "environment": "UNKNOWN",
    "resolution": "legacy-unresolved",
    "latestYm": "2026-02",
    "latestValue": 127.9,
    "latestTenants": 542,
    "unit": "days",
    "description": "Legacy workspace snapshot for Time to Fill. A current live metric_name match was not found in internal_usage_metrics_report_kafka during the 12 April 2026 refresh.",
    "notes": [
      "Preserved temporarily to avoid dropping the existing card before a clean live replacement is found.",
      "Do not attach a historical metric_id to this card until the live metric_name is revalidated."
    ],
    "series": []
  }
};

export const APPLICANT_VOLUME_BREAKDOWNS: Record<string, MetricSnapshot[]> = {
  "gender": [
    {
      "key": "femaleGender",
      "label": "Female",
      "metricName": "Count of job applications with female gender.",
      "metricId": 2339,
      "environment": "SANDBOX",
      "resolution": "live",
      "latestYm": "2026-02",
      "latestValue": 2302.7254475489376,
      "latestTenants": 5956,
      "unit": "count",
      "description": "Average number of job applications with female gender per reporting tenant for the month.",
      "notes": [],
      "series": [
        {
          "ym": "2023-11",
          "tenants": 4251,
          "avgValue": 2130.422383516741
        },
        {
          "ym": "2025-02",
          "tenants": 5283,
          "avgValue": 2528.2525977706405
        },
        {
          "ym": "2025-03",
          "tenants": 5339,
          "avgValue": 2677.0708411214955
        },
        {
          "ym": "2025-04",
          "tenants": 5263,
          "avgValue": 2625.540766021995
        },
        {
          "ym": "2025-05",
          "tenants": 5322,
          "avgValue": 2528.5589503280225
        },
        {
          "ym": "2025-06",
          "tenants": 5395,
          "avgValue": 2408.341400332533
        },
        {
          "ym": "2025-07",
          "tenants": 5415,
          "avgValue": 2596.223429729232
        },
        {
          "ym": "2025-08",
          "tenants": 5395,
          "avgValue": 2541.6352811870306
        },
        {
          "ym": "2025-09",
          "tenants": 5575,
          "avgValue": 2671.0519872249824
        },
        {
          "ym": "2025-10",
          "tenants": 5646,
          "avgValue": 2604.2068113640375
        },
        {
          "ym": "2025-11",
          "tenants": 5774,
          "avgValue": 2092.943370165746
        },
        {
          "ym": "2025-12",
          "tenants": 4971,
          "avgValue": 1100.6959728867623
        },
        {
          "ym": "2026-01",
          "tenants": 4841,
          "avgValue": 1754.2082304526748
        },
        {
          "ym": "2026-02",
          "tenants": 5956,
          "avgValue": 2302.7254475489376
        }
      ]
    },
    {
      "key": "maleGender",
      "label": "Male",
      "metricName": "Count of job applications with male gender.",
      "metricId": 2336,
      "environment": "SANDBOX",
      "resolution": "live",
      "latestYm": "2026-02",
      "latestValue": 2950.3260324360476,
      "latestTenants": 5960,
      "unit": "count",
      "description": "Average number of job applications with male gender per reporting tenant for the month.",
      "notes": [],
      "series": [
        {
          "ym": "2023-11",
          "tenants": 4245,
          "avgValue": 2416.6780773739742
        },
        {
          "ym": "2025-02",
          "tenants": 5287,
          "avgValue": 3193.7964885784404
        },
        {
          "ym": "2025-03",
          "tenants": 5329,
          "avgValue": 3330.6455056179775
        },
        {
          "ym": "2025-04",
          "tenants": 5261,
          "avgValue": 3195.1485204855844
        },
        {
          "ym": "2025-05",
          "tenants": 5310,
          "avgValue": 3024.607927860229
        },
        {
          "ym": "2025-06",
          "tenants": 5388,
          "avgValue": 2841.1084381939304
        },
        {
          "ym": "2025-07",
          "tenants": 5397,
          "avgValue": 3088.8190722602108
        },
        {
          "ym": "2025-08",
          "tenants": 5401,
          "avgValue": 3112.584522502744
        },
        {
          "ym": "2025-09",
          "tenants": 5578,
          "avgValue": 3328.4212577502212
        },
        {
          "ym": "2025-10",
          "tenants": 5634,
          "avgValue": 3179.5249380969226
        },
        {
          "ym": "2025-11",
          "tenants": 5775,
          "avgValue": 2631.207664422579
        },
        {
          "ym": "2025-12",
          "tenants": 4974,
          "avgValue": 1538.9882282521946
        },
        {
          "ym": "2026-01",
          "tenants": 4841,
          "avgValue": 2238.4423868312756
        },
        {
          "ym": "2026-02",
          "tenants": 5960,
          "avgValue": 2950.3260324360476
        }
      ]
    },
    {
      "key": "noGenderAssigned",
      "label": "No Gender Assigned",
      "metricName": "Count of job applications with no gender assigned.",
      "metricId": 2337,
      "environment": "SANDBOX",
      "resolution": "live",
      "latestYm": "2026-02",
      "latestValue": 3038.6575823440894,
      "latestTenants": 5960,
      "unit": "count",
      "description": "Average number of job applications with no gender assigned per reporting tenant for the month.",
      "notes": [],
      "series": [
        {
          "ym": "2023-11",
          "tenants": 4252,
          "avgValue": 2267.7895599250937
        },
        {
          "ym": "2025-02",
          "tenants": 5282,
          "avgValue": 2771.926303854875
        },
        {
          "ym": "2025-03",
          "tenants": 5332,
          "avgValue": 3023.8869548942544
        },
        {
          "ym": "2025-04",
          "tenants": 5257,
          "avgValue": 3058.2748671222475
        },
        {
          "ym": "2025-05",
          "tenants": 5312,
          "avgValue": 3178.620657276995
        },
        {
          "ym": "2025-06",
          "tenants": 5390,
          "avgValue": 2843.7322980218155
        },
        {
          "ym": "2025-07",
          "tenants": 5410,
          "avgValue": 3260.533923303835
        },
        {
          "ym": "2025-08",
          "tenants": 5410,
          "avgValue": 2777.6766532700035
        },
        {
          "ym": "2025-09",
          "tenants": 5575,
          "avgValue": 3204.1084914022335
        },
        {
          "ym": "2025-10",
          "tenants": 5645,
          "avgValue": 3200.2444405224146
        },
        {
          "ym": "2025-11",
          "tenants": 5774,
          "avgValue": 2663.4725483425414
        },
        {
          "ym": "2025-12",
          "tenants": 4969,
          "avgValue": 1606.6506890353505
        },
        {
          "ym": "2026-01",
          "tenants": 4836,
          "avgValue": 2444.213182286303
        },
        {
          "ym": "2026-02",
          "tenants": 5960,
          "avgValue": 3038.6575823440894
        }
      ]
    },
    {
      "key": "nonBinaryOrOtherGender",
      "label": "Non Male/Female Gender",
      "metricName": "Count of job applications with non male/female gender.",
      "metricId": 2338,
      "environment": "SANDBOX",
      "resolution": "live",
      "latestYm": "2026-02",
      "latestValue": 1504.6227424749163,
      "latestTenants": 5959,
      "unit": "count",
      "description": "Average number of job applications with non male/female gender per reporting tenant for the month.",
      "notes": [],
      "series": [
        {
          "ym": "2023-11",
          "tenants": 4256,
          "avgValue": 1450.609214218896
        },
        {
          "ym": "2025-02",
          "tenants": 5283,
          "avgValue": 1632.5684866805213
        },
        {
          "ym": "2025-03",
          "tenants": 5340,
          "avgValue": 1712.6426836105402
        },
        {
          "ym": "2025-04",
          "tenants": 5262,
          "avgValue": 1697.1784562867438
        },
        {
          "ym": "2025-05",
          "tenants": 5325,
          "avgValue": 1719.4662795054328
        },
        {
          "ym": "2025-06",
          "tenants": 5396,
          "avgValue": 1439.988734995383
        },
        {
          "ym": "2025-07",
          "tenants": 5414,
          "avgValue": 1726.8925939572587
        },
        {
          "ym": "2025-08",
          "tenants": 5403,
          "avgValue": 1617.8768301610542
        },
        {
          "ym": "2025-09",
          "tenants": 5579,
          "avgValue": 1693.0359737728159
        },
        {
          "ym": "2025-10",
          "tenants": 5644,
          "avgValue": 1659.7218005295674
        },
        {
          "ym": "2025-11",
          "tenants": 5777,
          "avgValue": 1405.5025021570318
        },
        {
          "ym": "2025-12",
          "tenants": 4970,
          "avgValue": 674.6292157254042
        },
        {
          "ym": "2026-01",
          "tenants": 4840,
          "avgValue": 979.6906770940523
        },
        {
          "ym": "2026-02",
          "tenants": 5959,
          "avgValue": 1504.6227424749163
        }
      ]
    }
  ],
  "raceEthnicity": [
    {
      "key": "blackOrAfricanAmerican",
      "label": "Black or African American",
      "metricName": "Count of job applications with a Black or African American ethnicity.",
      "metricId": 2376,
      "environment": "SANDBOX",
      "resolution": "live",
      "latestYm": "2026-02",
      "latestValue": 2431.690122012368,
      "latestTenants": 5963,
      "unit": "count",
      "description": "Average number of job applications with Black or African American ethnicity per reporting tenant for the month.",
      "notes": [],
      "series": [
        {
          "ym": "2023-11",
          "tenants": 4252,
          "avgValue": 2066.331070007024
        },
        {
          "ym": "2025-04",
          "tenants": 5298,
          "avgValue": 2662.5268412130345
        },
        {
          "ym": "2025-05",
          "tenants": 5348,
          "avgValue": 2666.7895129688372
        },
        {
          "ym": "2025-06",
          "tenants": 5425,
          "avgValue": 2392.0663115356356
        },
        {
          "ym": "2025-07",
          "tenants": 5430,
          "avgValue": 2693.6434606906687
        },
        {
          "ym": "2025-08",
          "tenants": 5394,
          "avgValue": 2540.0323879231473
        },
        {
          "ym": "2025-09",
          "tenants": 5578,
          "avgValue": 2675.7875309078063
        },
        {
          "ym": "2025-10",
          "tenants": 5623,
          "avgValue": 2602.637216713881
        },
        {
          "ym": "2025-11",
          "tenants": 5783,
          "avgValue": 2211.79055335287
        },
        {
          "ym": "2025-12",
          "tenants": 4969,
          "avgValue": 1200.8831869009584
        },
        {
          "ym": "2026-01",
          "tenants": 4865,
          "avgValue": 1879.7429858693426
        },
        {
          "ym": "2026-02",
          "tenants": 5963,
          "avgValue": 2431.690122012368
        }
      ]
    },
    {
      "key": "asian",
      "label": "Asian",
      "metricName": "Count of job applications with an Asian ethnicity.",
      "metricId": 2378,
      "environment": "SANDBOX",
      "resolution": "live",
      "latestYm": "2026-02",
      "latestValue": 2820.850551654965,
      "latestTenants": 5962,
      "unit": "count",
      "description": "Average number of job applications with Asian ethnicity per reporting tenant for the month.",
      "notes": [],
      "series": [
        {
          "ym": "2023-11",
          "tenants": 4254,
          "avgValue": 2166.2593025977067
        },
        {
          "ym": "2025-04",
          "tenants": 5294,
          "avgValue": 3029.996042216359
        },
        {
          "ym": "2025-05",
          "tenants": 5346,
          "avgValue": 2887.6404704125443
        },
        {
          "ym": "2025-06",
          "tenants": 5425,
          "avgValue": 2432.465748393021
        },
        {
          "ym": "2025-07",
          "tenants": 5429,
          "avgValue": 2973.0336211647987
        },
        {
          "ym": "2025-08",
          "tenants": 5384,
          "avgValue": 2824.189367552704
        },
        {
          "ym": "2025-09",
          "tenants": 5575,
          "avgValue": 3110.631215714033
        },
        {
          "ym": "2025-10",
          "tenants": 5623,
          "avgValue": 2941.4689325544346
        },
        {
          "ym": "2025-11",
          "tenants": 5781,
          "avgValue": 2498.3448870494913
        },
        {
          "ym": "2025-12",
          "tenants": 4972,
          "avgValue": 1284.703467516939
        },
        {
          "ym": "2026-01",
          "tenants": 4872,
          "avgValue": 2000.2482617586911
        },
        {
          "ym": "2026-02",
          "tenants": 5962,
          "avgValue": 2820.850551654965
        }
      ]
    },
    {
      "key": "white",
      "label": "White",
      "metricName": "Count of job applications with White ethnicity",
      "metricId": 2442,
      "environment": "SANDBOX",
      "resolution": "live",
      "latestYm": "2026-02",
      "latestValue": 2846.873326639893,
      "latestTenants": 5957,
      "unit": "count",
      "description": "Average number of job applications with White ethnicity per reporting tenant for the month.",
      "notes": [],
      "series": [
        {
          "ym": "2023-11",
          "tenants": 4260,
          "avgValue": 2488.27109137649
        },
        {
          "ym": "2025-04",
          "tenants": 5335,
          "avgValue": 3137.103441825664
        },
        {
          "ym": "2025-05",
          "tenants": 5390,
          "avgValue": 3009.230242457894
        },
        {
          "ym": "2025-06",
          "tenants": 5457,
          "avgValue": 2784.242191780822
        },
        {
          "ym": "2025-07",
          "tenants": 5514,
          "avgValue": 3061.849674384949
        },
        {
          "ym": "2025-08",
          "tenants": 5445,
          "avgValue": 2877.958310676092
        },
        {
          "ym": "2025-09",
          "tenants": 5635,
          "avgValue": 3126.452684974637
        },
        {
          "ym": "2025-10",
          "tenants": 5699,
          "avgValue": 3086.6640461215934
        },
        {
          "ym": "2025-11",
          "tenants": 5761,
          "avgValue": 2556.7018515314066
        },
        {
          "ym": "2025-12",
          "tenants": 4956,
          "avgValue": 1378.318118118118
        },
        {
          "ym": "2026-01",
          "tenants": 4832,
          "avgValue": 2266.1444765045344
        },
        {
          "ym": "2026-02",
          "tenants": 5957,
          "avgValue": 2846.873326639893
        }
      ]
    },
    {
      "key": "hispanicOrLatino",
      "label": "Hispanic or Latino",
      "metricName": "Count of job applications with Hispanic or Latino ethnicity",
      "metricId": 2439,
      "environment": "SANDBOX",
      "resolution": "live",
      "latestYm": "2026-02",
      "latestValue": 477.7718446601942,
      "latestTenants": 5955,
      "unit": "count",
      "description": "Average number of job applications with Hispanic or Latino ethnicity per reporting tenant for the month.",
      "notes": [],
      "series": [
        {
          "ym": "2023-11",
          "tenants": 4259,
          "avgValue": 460.1998597475456
        },
        {
          "ym": "2025-04",
          "tenants": 5335,
          "avgValue": 528.2072577628134
        },
        {
          "ym": "2025-05",
          "tenants": 5389,
          "avgValue": 528.4422436134765
        },
        {
          "ym": "2025-06",
          "tenants": 5459,
          "avgValue": 500.20230052948693
        },
        {
          "ym": "2025-07",
          "tenants": 5515,
          "avgValue": 529.0935069632845
        },
        {
          "ym": "2025-08",
          "tenants": 5451,
          "avgValue": 536.3420862006519
        },
        {
          "ym": "2025-09",
          "tenants": 5636,
          "avgValue": 556.8824969400245
        },
        {
          "ym": "2025-10",
          "tenants": 5703,
          "avgValue": 561.6998952513967
        },
        {
          "ym": "2025-11",
          "tenants": 5756,
          "avgValue": 476.805507447177
        },
        {
          "ym": "2025-12",
          "tenants": 4962,
          "avgValue": 242.91758351670333
        },
        {
          "ym": "2026-01",
          "tenants": 4837,
          "avgValue": 365.62301832406837
        },
        {
          "ym": "2026-02",
          "tenants": 5955,
          "avgValue": 477.7718446601942
        }
      ]
    },
    {
      "key": "twoOrMoreRaces",
      "label": "Two or More Races",
      "metricName": "Count of job applications with Two or More Races ethnicity",
      "metricId": 2438,
      "environment": "SANDBOX",
      "resolution": "live",
      "latestYm": "2026-02",
      "latestValue": 2225.6666666666665,
      "latestTenants": 5954,
      "unit": "count",
      "description": "Average number of job applications with Two or More Races ethnicity per reporting tenant for the month.",
      "notes": [],
      "series": [
        {
          "ym": "2023-11",
          "tenants": 4256,
          "avgValue": 1839.0491228070175
        },
        {
          "ym": "2025-04",
          "tenants": 5335,
          "avgValue": 2488.0065469509914
        },
        {
          "ym": "2025-05",
          "tenants": 5389,
          "avgValue": 2409.9640873750463
        },
        {
          "ym": "2025-06",
          "tenants": 5458,
          "avgValue": 2243.5067567567567
        },
        {
          "ym": "2025-07",
          "tenants": 5516,
          "avgValue": 2491.3471971066906
        },
        {
          "ym": "2025-08",
          "tenants": 5447,
          "avgValue": 2280.658028271113
        },
        {
          "ym": "2025-09",
          "tenants": 5636,
          "avgValue": 2529.8081832488197
        },
        {
          "ym": "2025-10",
          "tenants": 5705,
          "avgValue": 2444.797033158813
        },
        {
          "ym": "2025-11",
          "tenants": 5762,
          "avgValue": 2021.6480968858132
        },
        {
          "ym": "2025-12",
          "tenants": 4966,
          "avgValue": 1032.2461630456448
        },
        {
          "ym": "2026-01",
          "tenants": 4840,
          "avgValue": 1686.8471193415637
        },
        {
          "ym": "2026-02",
          "tenants": 5954,
          "avgValue": 2225.6666666666665
        }
      ]
    }
  ],
  "age": [
    {
      "key": "age17AndBelow",
      "label": "Age 17 and Below",
      "metricName": "Number of job applications with candidates aged 17 and below",
      "metricId": 2359,
      "environment": "SANDBOX",
      "resolution": "live",
      "latestYm": "2026-02",
      "latestValue": 11.595851455336232,
      "latestTenants": 5957,
      "unit": "count",
      "description": "Average number of job applications with candidates aged 17 and below per reporting tenant for the month.",
      "notes": [],
      "series": [
        {
          "ym": "2023-11",
          "tenants": 4238,
          "avgValue": 8.40662438336857
        },
        {
          "ym": "2025-04",
          "tenants": 5323,
          "avgValue": 12.157450796626055
        },
        {
          "ym": "2025-05",
          "tenants": 5355,
          "avgValue": 14.562325321408608
        },
        {
          "ym": "2025-06",
          "tenants": 5443,
          "avgValue": 16.94506500640908
        },
        {
          "ym": "2025-07",
          "tenants": 5471,
          "avgValue": 18.690610756608933
        },
        {
          "ym": "2025-08",
          "tenants": 5470,
          "avgValue": 16.82079047103411
        },
        {
          "ym": "2025-09",
          "tenants": 5646,
          "avgValue": 16.571328548923507
        },
        {
          "ym": "2025-10",
          "tenants": 5675,
          "avgValue": 17.604426488670295
        },
        {
          "ym": "2025-11",
          "tenants": 5785,
          "avgValue": 11.823194899190074
        },
        {
          "ym": "2025-12",
          "tenants": 4965,
          "avgValue": 10.946653346653347
        },
        {
          "ym": "2026-01",
          "tenants": 4863,
          "avgValue": 9.426874231872183
        },
        {
          "ym": "2026-02",
          "tenants": 5957,
          "avgValue": 11.595851455336232
        }
      ]
    },
    {
      "key": "age18To24",
      "label": "Age 18-24",
      "metricName": "Number of job applications with candidates aged between 18 and 24 created in the last month.",
      "metricId": 2429,
      "environment": "SANDBOX",
      "resolution": "live",
      "latestYm": "2026-02",
      "latestValue": 178.7643610785463,
      "latestTenants": 5952,
      "unit": "count",
      "description": "Average number of job applications with candidates aged 18-24 per reporting tenant for the month.",
      "notes": [],
      "series": [
        {
          "ym": "2023-11",
          "tenants": 4259,
          "avgValue": 145.43595137914915
        },
        {
          "ym": "2025-04",
          "tenants": 5359,
          "avgValue": 170.2270018621974
        },
        {
          "ym": "2025-05",
          "tenants": 5414,
          "avgValue": 205.20504789977892
        },
        {
          "ym": "2025-06",
          "tenants": 5484,
          "avgValue": 202.37609011627907
        },
        {
          "ym": "2025-07",
          "tenants": 5524,
          "avgValue": 224.65174219173136
        },
        {
          "ym": "2025-08",
          "tenants": 5457,
          "avgValue": 176.03752039151712
        },
        {
          "ym": "2025-09",
          "tenants": 5650,
          "avgValue": 213.6770088896636
        },
        {
          "ym": "2025-10",
          "tenants": 5706,
          "avgValue": 209.4747686397765
        },
        {
          "ym": "2025-11",
          "tenants": 5764,
          "avgValue": 178.53908682116915
        },
        {
          "ym": "2025-12",
          "tenants": 4981,
          "avgValue": 67.19952162647
        },
        {
          "ym": "2026-01",
          "tenants": 4844,
          "avgValue": 126.54575365001028
        },
        {
          "ym": "2026-02",
          "tenants": 5952,
          "avgValue": 178.7643610785463
        }
      ]
    },
    {
      "key": "age25To34",
      "label": "Age 25-34",
      "metricName": "Number of job applications with candidates aged between 25 and 34 created in the last month.",
      "metricId": 2432,
      "environment": "SANDBOX",
      "resolution": "live",
      "latestYm": "2026-02",
      "latestValue": 258.29252383341696,
      "latestTenants": 5960,
      "unit": "count",
      "description": "Average number of job applications with candidates aged 25-34 per reporting tenant for the month.",
      "notes": [],
      "series": [
        {
          "ym": "2023-11",
          "tenants": 4252,
          "avgValue": 179.85998595176773
        },
        {
          "ym": "2025-04",
          "tenants": 5336,
          "avgValue": 243.38544978492612
        },
        {
          "ym": "2025-05",
          "tenants": 5397,
          "avgValue": 255.828280961183
        },
        {
          "ym": "2025-06",
          "tenants": 5457,
          "avgValue": 244.25808219178083
        },
        {
          "ym": "2025-07",
          "tenants": 5519,
          "avgValue": 287.69853605638895
        },
        {
          "ym": "2025-08",
          "tenants": 5453,
          "avgValue": 251.57432554770958
        },
        {
          "ym": "2025-09",
          "tenants": 5637,
          "avgValue": 261.9395421981478
        },
        {
          "ym": "2025-10",
          "tenants": 5705,
          "avgValue": 237.83577661431065
        },
        {
          "ym": "2025-11",
          "tenants": 5765,
          "avgValue": 230.8120352758084
        },
        {
          "ym": "2025-12",
          "tenants": 4973,
          "avgValue": 108.79516869634658
        },
        {
          "ym": "2026-01",
          "tenants": 4842,
          "avgValue": 149.5826820238585
        },
        {
          "ym": "2026-02",
          "tenants": 5960,
          "avgValue": 258.29252383341696
        }
      ]
    },
    {
      "key": "age35To44",
      "label": "Age 35-44",
      "metricName": "Number of job applications with candidates aged between 35 and 44 created in the last month.",
      "metricId": 2430,
      "environment": "SANDBOX",
      "resolution": "live",
      "latestYm": "2026-02",
      "latestValue": 96.94726268206931,
      "latestTenants": 5954,
      "unit": "count",
      "description": "Average number of job applications with candidates aged 35-44 per reporting tenant for the month.",
      "notes": [],
      "series": [
        {
          "ym": "2023-11",
          "tenants": 4259,
          "avgValue": 75.76273959794297
        },
        {
          "ym": "2025-04",
          "tenants": 5359,
          "avgValue": 95.79459962756052
        },
        {
          "ym": "2025-05",
          "tenants": 5416,
          "avgValue": 97.04180478821362
        },
        {
          "ym": "2025-06",
          "tenants": 5482,
          "avgValue": 90.05380839847301
        },
        {
          "ym": "2025-07",
          "tenants": 5536,
          "avgValue": 110.4755899837867
        },
        {
          "ym": "2025-08",
          "tenants": 5471,
          "avgValue": 97.2203573362209
        },
        {
          "ym": "2025-09",
          "tenants": 5651,
          "avgValue": 98.04744461887319
        },
        {
          "ym": "2025-10",
          "tenants": 5703,
          "avgValue": 98.24847108160056
        },
        {
          "ym": "2025-11",
          "tenants": 5769,
          "avgValue": 90.2775185761189
        },
        {
          "ym": "2025-12",
          "tenants": 4974,
          "avgValue": 40.84051896207585
        },
        {
          "ym": "2026-01",
          "tenants": 4838,
          "avgValue": 55.96479308214948
        },
        {
          "ym": "2026-02",
          "tenants": 5954,
          "avgValue": 96.94726268206931
        }
      ]
    },
    {
      "key": "age45To54",
      "label": "Age 45-54",
      "metricName": "Number of job applications with candidates aged between 45 and 54 created in the last month.",
      "metricId": 2428,
      "environment": "SANDBOX",
      "resolution": "live",
      "latestYm": "2026-02",
      "latestValue": 35.8979250334672,
      "latestTenants": 5956,
      "unit": "count",
      "description": "Average number of job applications with candidates aged 45-54 per reporting tenant for the month.",
      "notes": [],
      "series": [
        {
          "ym": "2023-11",
          "tenants": 4252,
          "avgValue": 30.38337236533958
        },
        {
          "ym": "2025-04",
          "tenants": 5355,
          "avgValue": 34.872554499720515
        },
        {
          "ym": "2025-05",
          "tenants": 5404,
          "avgValue": 34.587963817611225
        },
        {
          "ym": "2025-06",
          "tenants": 5476,
          "avgValue": 32.62989259056982
        },
        {
          "ym": "2025-07",
          "tenants": 5519,
          "avgValue": 40.06849810229532
        },
        {
          "ym": "2025-08",
          "tenants": 5473,
          "avgValue": 36.20576576576577
        },
        {
          "ym": "2025-09",
          "tenants": 5653,
          "avgValue": 36.958856345885636
        },
        {
          "ym": "2025-10",
          "tenants": 5704,
          "avgValue": 38.048567435359885
        },
        {
          "ym": "2025-11",
          "tenants": 5768,
          "avgValue": 34.38696854476322
        },
        {
          "ym": "2025-12",
          "tenants": 4973,
          "avgValue": 15.510362694300518
        },
        {
          "ym": "2026-01",
          "tenants": 4840,
          "avgValue": 19.15579337312204
        },
        {
          "ym": "2026-02",
          "tenants": 5956,
          "avgValue": 35.8979250334672
        }
      ]
    },
    {
      "key": "age55To64",
      "label": "Age 55-64",
      "metricName": "Number of job applications with candidates aged between 55 and 64 created in the last month.",
      "metricId": 2433,
      "environment": "SANDBOX",
      "resolution": "live",
      "latestYm": "2026-02",
      "latestValue": 11.993142665997658,
      "latestTenants": 5960,
      "unit": "count",
      "description": "Average number of job applications with candidates aged 55-64 per reporting tenant for the month.",
      "notes": [],
      "series": [
        {
          "ym": "2023-11",
          "tenants": 4255,
          "avgValue": 8.753568921132693
        },
        {
          "ym": "2025-04",
          "tenants": 5333,
          "avgValue": 12.855351796407186
        },
        {
          "ym": "2025-05",
          "tenants": 5394,
          "avgValue": 12.322729794710561
        },
        {
          "ym": "2025-06",
          "tenants": 5462,
          "avgValue": 11.607116788321168
        },
        {
          "ym": "2025-07",
          "tenants": 5518,
          "avgValue": 13.890817064352856
        },
        {
          "ym": "2025-08",
          "tenants": 5450,
          "avgValue": 12.756928092736823
        },
        {
          "ym": "2025-09",
          "tenants": 5636,
          "avgValue": 13.523684670512148
        },
        {
          "ym": "2025-10",
          "tenants": 5704,
          "avgValue": 13.948682143480537
        },
        {
          "ym": "2025-11",
          "tenants": 5755,
          "avgValue": 12.621167503897453
        },
        {
          "ym": "2025-12",
          "tenants": 4969,
          "avgValue": 6.578390253644897
        },
        {
          "ym": "2026-01",
          "tenants": 4843,
          "avgValue": 8.910754678182192
        },
        {
          "ym": "2026-02",
          "tenants": 5960,
          "avgValue": 11.993142665997658
        }
      ]
    },
    {
      "key": "age65Plus",
      "label": "Age 65+",
      "metricName": "Number of job applications with candidates aged 65 or over created in the last month.",
      "metricId": 2427,
      "environment": "SANDBOX",
      "resolution": "live",
      "latestYm": "2026-02",
      "latestValue": 1.7207900903916973,
      "latestTenants": 5954,
      "unit": "count",
      "description": "Average number of job applications with candidates aged 65 or over per reporting tenant for the month.",
      "notes": [],
      "series": [
        {
          "ym": "2023-11",
          "tenants": 4253,
          "avgValue": 1.3369234371341605
        },
        {
          "ym": "2025-04",
          "tenants": 5359,
          "avgValue": 1.794451684974865
        },
        {
          "ym": "2025-05",
          "tenants": 5401,
          "avgValue": 1.8073513114148503
        },
        {
          "ym": "2025-06",
          "tenants": 5468,
          "avgValue": 1.7289958082741024
        },
        {
          "ym": "2025-07",
          "tenants": 5519,
          "avgValue": 1.9338514368335442
        },
        {
          "ym": "2025-08",
          "tenants": 5470,
          "avgValue": 2.0869565217391304
        },
        {
          "ym": "2025-09",
          "tenants": 5663,
          "avgValue": 2.201009397841977
        },
        {
          "ym": "2025-10",
          "tenants": 5717,
          "avgValue": 2.245121951219512
        },
        {
          "ym": "2025-11",
          "tenants": 5770,
          "avgValue": 1.8975466482377332
        },
        {
          "ym": "2025-12",
          "tenants": 4975,
          "avgValue": 0.8717846460618146
        },
        {
          "ym": "2026-01",
          "tenants": 4840,
          "avgValue": 1.0802634286890307
        },
        {
          "ym": "2026-02",
          "tenants": 5954,
          "avgValue": 1.7207900903916973
        }
      ]
    }
  ]
};

