#!/usr/bin/env python3
"""Materialise Employment Agreement sub-BP rows + step series for the BP Durations dashboard."""

from __future__ import annotations

import csv
import io
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EA_DUR_PATH = ROOT / "design" / "data-employment-agreement-durations.ts"
EA_STEPS_PATH = ROOT / "design" / "data-employment-agreement-steps.ts"

AGG_JSON = Path("/tmp/ea_agg.json")
STEPS_JSON = Path("/tmp/ea_steps.json")


def num_or_null(s: str, as_int: bool = False):
    if s is None or s == "":
        return "null"
    try:
        v = float(s)
        if as_int:
            return str(int(round(v)))
        if v == int(v):
            return str(int(v))
        return str(round(v, 4)).rstrip("0").rstrip(".")
    except ValueError:
        return "null"


def esc_js(s: str) -> str:
    return json.dumps(s)


def row_to_tuple(row: dict) -> str:
    scope = row["scope"]
    scope_val = row["scope_value"] or ""
    if scope == "global":
        slice_key = ""
    else:
        slice_key = scope_val
    ym = row["ym"]
    status = row["status"]
    events = num_or_null(row["events"], as_int=True)
    tenants = num_or_null(row["tenants"], as_int=True)
    avg_d = num_or_null(row["avg_days"])
    med_d = num_or_null(row["median_days"])
    avg_st = num_or_null(row["avg_steps"])
    psb = num_or_null(row["pct_sent_back"])
    pcr = num_or_null(row["pct_corrected"])
    pra = num_or_null(row["pct_reassigned"])
    region = row.get("region") or ""
    industry = row.get("industry") or ""
    return (
        f"  [{esc_js(slice_key)}, \"employment_agreement\", {esc_js(ym)}, {esc_js(status)}, "
        f"{events}, {tenants}, {avg_d}, {med_d}, {avg_st}, {psb}, {pcr}, {pra}, "
        f"{esc_js(region)}, {esc_js(industry)}],"
    )


def write_durations(rows: list[dict]) -> None:
    buckets = {"global": [], "region": [], "industry": [], "tenant": []}
    for row in rows:
        buckets[row["scope"]].append(row_to_tuple(row))

    header = """/**
 * Employment Agreement sub-BP aggregates (PROD, Pharos).
 * BP type: Propose Compensation Offer/Employment Agreement
 * Source: dw.swh.bp_event_stats + tenant enrichment join (same pattern as data-bp-durations.ts)
 * Generated by scripts/build_employment_agreement_dashboard_data.py
 */

import type { AggTuple } from './data-bp-durations';

export const EMPLOYMENT_AGREEMENT_BP_TYPE_ID =
  'Propose Compensation Offer/Employment Agreement' as const;

export const EMPLOYMENT_AGREEMENT_SUB_BP_META = {
  key: 'employment_agreement',
  label: 'Employment Agreement',
  description:
    'Propose Compensation Offer/Employment Agreement — compensation and employment agreement flow used alongside or instead of Offer for some tenants. Event-level stats from dw.swh.bp_event_stats (PROD), months aligned to LABELS in data-bp-durations.ts.',
} as const;

export const EMPLOYMENT_AGREEMENT_GLOBAL_ROWS: AggTuple[] = [
"""
    parts = [header]
    parts.append("\n".join(buckets["global"]))
    parts.append(
        """];

export const EMPLOYMENT_AGREEMENT_REGION_ROWS: AggTuple[] = [
"""
    )
    parts.append("\n".join(buckets["region"]))
    parts.append(
        """];

export const EMPLOYMENT_AGREEMENT_INDUSTRY_ROWS: AggTuple[] = [
"""
    )
    parts.append("\n".join(buckets["industry"]))
    parts.append(
        """];

export const EMPLOYMENT_AGREEMENT_TENANT_ROWS: AggTuple[] = [
"""
    )
    parts.append("\n".join(buckets["tenant"]))
    parts.append("];\n")
    EA_DUR_PATH.write_text("\n".join(parts))


def write_steps(rows: list[dict]) -> None:
    by_task: dict[str, list[dict]] = {}
    for row in rows:
        by_task.setdefault(row["task_name"], []).append(row)
    for t in by_task:
        by_task[t].sort(key=lambda r: r["ym"])

    tasks_sorted = sorted(by_task.keys())

    lines = [
        "/**",
        " * Employment Agreement BP step-level metrics (PROD, Pharos).",
        " * BP type: Propose Compensation Offer/Employment Agreement",
        " * Source: dw.swh.bp_event_record_stats",
        " * Generated by scripts/build_employment_agreement_dashboard_data.py",
        " */",
        "",
        "import { LABELS } from './data-bp-durations';",
        "",
        "export interface EaStepMonthlyPoint {",
        "  ym: string;",
        "  volume: number;",
        "  tenants: number;",
        "  avgHours: number | null;",
        "  p90Hours: number | null;",
        "}",
        "",
        "export const EMPLOYMENT_AGREEMENT_STEPS_SOURCE = {",
        "  table: 'dw.swh.bp_event_record_stats',",
        "  environment: 'PROD',",
        f"  bpTypeId: {json.dumps('Propose Compensation Offer/Employment Agreement')},",
        "  monthRange: '2025-04 to 2026-03',",
        "} as const;",
        "",
        "/** Curated tasks aligned to Offer dashboard (document, integration, approval). */",
        "export const EA_DOCUMENT_STEP_TASKS = [",
        ' "Review Documents",',
        '  "Review Writer Generated Document",',
        '  "Add Documents",',
        '  "Generate Document",',
        '  "Manage Attachments",',
        '  "Put Review Document Event for eSignature Integration (Web Service)",',
        "] as const;",
        "",
        "export const EA_INTEGRATION_STEP_TASKS = [",
        '  "Complete Questionnaire",',
        '  "Employment Agreement (Web Service)",',
        '  "Offer (Web Service)",',
        "] as const;",
        "",
        "export const EA_APPROVAL_STEP_TASKS = [",
        '  "Bulk Approve",',
        '  "Approve Business Process (Web Service)",',
        "] as const;",
        "",
        "export const employmentAgreementStepMonthly: Record<string, EaStepMonthlyPoint[]> = {",
    ]

    def fmt_point(r: dict) -> str:
        vol = int(r["volume"])
        ten = int(r["tenants"])
        ah = r.get("avg_hours") or ""
        p90 = r.get("p90_hours") or ""
        avg_js = "null" if ah == "" else str(float(ah))
        p90_js = "null" if p90 == "" else str(float(p90))
        return f'{{"ym":{json.dumps(r["ym"])}, "volume":{vol}, "tenants":{ten}, "avgHours":{avg_js}, "p90Hours":{p90_js}}}'

    for task in tasks_sorted:
        pts = ", ".join(fmt_point(r) for r in by_task[task])
        lines.append(f"  {json.dumps(task)}: [{pts}],")

    lines.extend(
        [
            "};",
            "",
            "export function eaStepsLatestYm(): string {",
            " return LABELS[LABELS.length - 1]!;",
            "}",
            "",
            "export function bottleneckScoreEa(volume: number, avgHours: number | null): number {",
            "  if (avgHours == null || avgHours <= 0) return 0;",
            "  const v = Math.max(0, volume);",
            "  return avgHours * Math.log10(1 + v);",
            "}",
            "",
            "export type EaBottleneckRow = {",
            "  taskName: string;",
            "  group: 'document' | 'integration' | 'approval';",
            "  latestYm: string;",
            "  volume: number;",
            "  tenants: number;",
            "  avgHours: number | null;",
            "  p90Hours: number | null;",
            "  score: number;",
            "  dominantFactor: 'volume' | 'duration' | 'low_tenant_coverage';",
            "};",
            "",
            "function pointEa(task: string, ym: string): EaStepMonthlyPoint | undefined {",
            "  return employmentAgreementStepMonthly[task]?.find(p => p.ym === ym);",
            "}",
            "",
            "export function rankEmploymentAgreementBottlenecks(ym: string = eaStepsLatestYm()): EaBottleneckRow[] {",
            "  const rows: EaBottleneckRow[] = [];",
            "  const push = (taskName: string, group: EaBottleneckRow['group']) => {",
            "    const p = pointEa(taskName, ym);",
            "    if (!p) return;",
            "    const score = bottleneckScoreEa(p.volume, p.avgHours);",
            "    let dominantFactor: EaBottleneckRow['dominantFactor'] = 'volume';",
            "    if (p.tenants > 0 && p.volume / p.tenants < 50) dominantFactor = 'low_tenant_coverage';",
            "    if (p.avgHours != null && p.avgHours >= 8 && p.volume > 5000) dominantFactor = 'duration';",
            "    rows.push({ taskName, group, latestYm: ym, volume: p.volume, tenants: p.tenants, avgHours: p.avgHours, p90Hours: p.p90Hours, score, dominantFactor });",
            "  };",
            "  for (const t of EA_DOCUMENT_STEP_TASKS) push(t, 'document');",
            "  for (const t of EA_INTEGRATION_STEP_TASKS) push(t, 'integration');",
            "  for (const t of EA_APPROVAL_STEP_TASKS) push(t, 'approval');",
            "  return rows.sort((a, b) => b.score - a.score);",
            "}",
            "",
            "export const HAS_EA_APPROVAL_CHARTS = true;",
            "",
        ]
    )
    EA_STEPS_PATH.write_text("\n".join(lines) + "\n")


def main() -> None:
    agg = json.loads(AGG_JSON.read_text())
    step = json.loads(STEPS_JSON.read_text())
    agg_rows = list(csv.DictReader(io.StringIO(agg["result"]["data"])))
    step_rows = list(csv.DictReader(io.StringIO(step["result"]["data"])))
    write_durations(agg_rows)
    write_steps(step_rows)
    print(f"Wrote {EA_DUR_PATH} ({len(agg_rows)} agg rows)")
    print(f"Wrote {EA_STEPS_PATH} ({len(step_rows)} step rows)")


if __name__ == "__main__":
    main()
