#!/usr/bin/env python3
"""Build shared tenant filter metadata for dashboard scoping.

Creates a TypeScript module that materialises:
- tenant company-size / region / industry enrichment
- recruiter-capacity monthly tenant series

Source of truth:
- dw.user_test.interview_dashboard_tenant_filters
- dw.swh_raw.internal_usage_metrics_report_kafka
"""

from __future__ import annotations

import csv
import io
import json
import subprocess
import textwrap
from collections import defaultdict
from datetime import date
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT / "design" / "data-dashboard-tenant-filters.ts"
PHAROS_BIN = Path("/Users/david.denham/.local/bin/pharos")


def run_pharos_sql(sql: str) -> list[dict[str, str]]:
    env = {
        "PATH": f"{PHAROS_BIN.parent}:{PHAROS_BIN.parent.parent / 'bin'}:/usr/bin:/bin",
    }
    result = subprocess.run(
        [str(PHAROS_BIN), "sql", "run", "--sql", sql],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
        env=env,
    )

    payload_line = None
    for line in reversed(result.stdout.splitlines()):
        line = line.strip()
        if line.startswith("{") and '"result"' in line:
            payload_line = line
            break
    if payload_line is None:
        raise RuntimeError("No JSON payload found in pharos output")

    payload = json.loads(payload_line)
    csv_text = payload["result"]["data"]
    reader = csv.DictReader(io.StringIO(csv_text))
    return list(reader)


def normalise(value: str | None, fallback: str = "Unknown") -> str:
    cleaned = (value or "").strip()
    return cleaned or fallback


def build_metadata() -> tuple[dict[str, dict[str, str]], list[str], list[str], list[str]]:
    rows = run_pharos_sql(
        textwrap.dedent(
            """
            SELECT tenant_name, company_size, segment, super_industry
            FROM dw.user_test.interview_dashboard_tenant_filters
            """
        ).strip()
    )

    metadata: dict[str, dict[str, str]] = {}
    segments: set[str] = set()
    regions: set[str] = set()
    industries: set[str] = set()

    for row in rows:
        tenant = normalise(row.get("tenant_name"), "").lower()
        if not tenant:
            continue
        segment = normalise(row.get("company_size"))
        region = normalise(row.get("segment"))
        industry = normalise(row.get("super_industry"))
        metadata[tenant] = {
            "segment": segment,
            "region": region,
            "industry": industry,
        }
        segments.add(segment)
        regions.add(region)
        industries.add(industry)

    return (
        dict(sorted(metadata.items())),
        sorted(segments),
        sorted(regions),
        sorted(industries),
    )


def build_recruiter_capacity_series() -> dict[str, list[dict[str, float | str]]]:
    rows = run_pharos_sql(
        textwrap.dedent(
            """
            SELECT
              lower(tenant_name) AS tenant_name,
              CONCAT(CAST(year AS varchar), '-', LPAD(CAST(month AS varchar), 2, '0')) AS ym,
              ROUND(AVG(try_cast(value AS double)), 4) AS avg_value
            FROM dw.swh_raw.internal_usage_metrics_report_kafka
            WHERE wd_event_date >= to_iso8601(current_date - interval '365' day)
              AND metric_name = 'Recruiter Productivity'
              AND wd_env_type = 'SANDBOX'
              AND try_cast(value AS double) > 0
            GROUP BY 1, 2
            HAVING CONCAT(CAST(year AS varchar), '-', LPAD(CAST(month AS varchar), 2, '0')) >= '2025-06'
            ORDER BY 1, 2
            """
        ).strip()
    )

    series_by_tenant: dict[str, list[dict[str, float | str]]] = defaultdict(list)
    for row in rows:
        tenant = normalise(row.get("tenant_name"), "").lower()
        ym = normalise(row.get("ym"), "")
        value_raw = normalise(row.get("avg_value"), "")
        if not tenant or not ym or not value_raw:
            continue
        series_by_tenant[tenant].append({"ym": ym, "value": round(float(value_raw), 4)})
    return dict(sorted(series_by_tenant.items()))


def to_ts(value: object) -> str:
    return json.dumps(value, indent=2, sort_keys=True)


def main() -> None:
    metadata, segments, regions, industries = build_metadata()
    recruiter_capacity = build_recruiter_capacity_series()

    contents = f"""// Auto-generated by scripts/build_dashboard_tenant_filter_data.py
// Source: dw.user_test.interview_dashboard_tenant_filters + Recruiter Productivity IUM
// Generated: {date.today().isoformat()}

export type DashboardTenantFilterMeta = {{
  segment: string;
  region: string;
  industry: string;
}};

export const TENANT_FILTER_METADATA: Record<string, DashboardTenantFilterMeta> = {to_ts(metadata)} as const;

export const SEGMENT_OPTIONS = {to_ts(segments)} as const;
export const REGION_OPTIONS = {to_ts(regions)} as const;
export const INDUSTRY_OPTIONS = {to_ts(industries)} as const;

export const RECRUITER_CAPACITY_TENANT_SERIES: Record<string, Array<{{ ym: string; value: number }}>> = {to_ts(recruiter_capacity)} as const;
"""
    OUTPUT_PATH.write_text(contents)
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
